# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target '8477_Daniella Queiroz_ applicationPrototype' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for 8477_Daniella Queiroz_ applicationPrototype

	pod 'Firebase/Auth'
	pod 'Firebase/Firestore'
	pod 'Firebase/Database'

  target '8477_Daniella Queiroz_ applicationPrototypeTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target '8477_Daniella Queiroz_ applicationPrototypeUITests' do
    # Pods for testing
  end

end
